### ISSUE TITLE
Text in Project Settings remains black in dark mode

### ISSUE THREAD

**Issue by zhekaiii** [Project-Trofos/trofos#181]
**Describe the bug**
Email notification under project settings do not follow the theme text colour, causing it to remain as black when in dark mode.

**To Reproduce**
1. Go to any project
2. Click on settings
3. Scroll down to "User Settings"

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/adae0cb5-0b81-42e0-8f9e-b6878be212dc)

**Comment by bokuanT** [comment]
#200 will fix this
